--DNM

SELECT * FROM JCREW.LP_EXT_DONOTMAIL ORDER BY LIneID DESC LIMIT 100;

SELECT MAX(LIneID) FROM JCREW.LP_EXT_DONOTMAIL;
--226001

INSERT INTO JCREW.LP_EXT_DONOTMAIL
SELECT 'N/A', 'Gavin','Morgan','420 Shady Ln','','Wenatchee','WA','98801-2435','','','',226002,'Manually inserted',CURRENT_DATE() UNION ALL
SELECT 'N/A', 'Gavin','Morgan','3720 S Palm Springs St','','Nampa','ID','83686-5681','','','',226003,'Manually inserted',CURRENT_DATE()
ORDER BY 12
;

SELECT CONCAT(REPEAT('0',5-LEN(Zip)),ZIP)
FROM JCREW.LP_EXT_DONOTMAIL
WHERE LEN(Zip) < 5;

UPDATE JCREW.LP_EXT_DONOTMAIL
SET ZIP = CONCAT(REPEAT('0',5-LEN(Zip)),ZIP)
WHERE LEN(Zip) < 5;
--27

SELECT * FROM JCREW.LP_INT_AdditionalAddressSuppression ORDER BY LineID DESC LIMIT 100;

SELECT MAX(LIneID) FROM JCREW.LP_INT_AdditionalAddressSuppression;
--2780

DELETE FROM JCREW.LP_INT_AdditionalAddressSuppression WHERE LINEID IN (
SELECT LineID
FROM JCREW.LP_INT_AdditionalAddressSuppression
GROUP BY LineID
HAVING COUNT(*) > 1);

INSERT INTO JCREW.LP_INT_AdditionalAddressSuppression
SELECT 2781,'420 Shady Ln','','Wenatchee','WA','98801-2435','Manually inserted',CURRENT_DATE(),0 UNION ALL
SELECT 2782,'3720 S Palm Springs St','','Nampa','ID','83686-5681','Manually inserted',CURRENT_DATE(),0 
;

SELECT CONCAT(REPEAT('0',5-LEN(Zip)),ZIP)
FROM JCREW.LP_INT_AdditionalAddressSuppression
WHERE LEN(Zip) < 5;

UPDATE JCREW.LP_INT_AdditionalAddressSuppression
SET ZIP = CONCAT(REPEAT('0',5-LEN(Zip)),ZIP)
WHERE LEN(Zip) < 5;
--27
