----------------------------------------------------------------
----- Lafayette Do Not Mail ------------------------------------
----------------------------------------------------------------
TRUNCATE TABLE LAFAYETTE.LP_INT_DONOTMAIL_STAGE;

SET STARTLINEID = (SELECT MAX(LINEID) AS LineID FROM LAFAYETTE.LP_INT_DONOTMAIL);

INSERT INTO LAFAYETTE.LP_INT_DONOTMAIL
SELECT $STARTLINEID+ROW_NUMBER() OVER(ORDER BY RANDOM()) AS LineID,DATE,NAME,ADDRESS,CITY,STATE,ZIP,SOURCECODE,'SUPPRESSION FILE_SEPT 24 BOOK',CURRENT_TIMESTAMP()
FROM LAFAYETTE.LP_INT_DONOTMAIL_STAGE
WHERE UPPER(ADDRESS || CITY || STATE || ZIP) NOT IN (SELECT UPPER("STREET ADDRESS" || CITY || STATE || "ZIP CODE") FROM LAFAYETTE.LP_INT_DONOTMAIL);
--24

SELECT * FROM LAFAYETTE.LP_INT_DONOTMAIL
WHERE "STREET ADDRESS" = 'PO Box 3355';

SELECT * FROM LAFAYETTE.LP_INT_DONOTMAIL_STAGE
WHERE ADDRESS = 'PO Box 3355';
--Nancy Rayner	PO Box 3355	long beach	ca	90803-0355	M15MR2004A

SELECT COUNT(*) FROM LAFAYETTE.LP_INT_DONOTMAIL;