SELECT *
FROM JCREW.LP_EXT_DONOTMAIL
WHERE Address1 LIKE '%5302%'
AND Zip LIKE '%75035%'
;

SELECT *
FROM JCREW.LP_INT_AdditionalAddressSuppression
WHERE Address1 LIKE '%5302%'
AND Zip LIKE '%75035%'
;

SELECT *
FROM JCREW.LP_JCR2504_MAILFILE
WHERE STREET_C LIKE '%5302%'
AND STATE_C = 'TX'
--AND ZIP_C LIKE '%75035%'
;

SELECT FIRST_C,LAST_C,STREET_C,STREET2_C,CITY_C,STATE_C,ZIP_C,isMailed,isHoldout,FileName
FROM JCREW.LP_FAC2416_MAILFILE
WHERE STREET_C LIKE '%BOX%5302%'
AND STATE_C = 'TX'
AND (ismailed = 1 OR isHoldout = 1);