CREATE OR REPLACE TABLE JCREW.LP_JCR2503_IQ
(
Priority INT,MastercustomerID VARCHAR,SourceCustomerNumber VARCHAR,Email VARCHAR,EmailStatus VARCHAR,FirstName VARCHAR,MiddleName VARCHAR,LastName VARCHAR,Address1 VARCHAR,Address2 VARCHAR,Suite VARCHAR,City VARCHAR,State VARCHAR,ZipCode VARCHAR,ZipEXT VARCHAR,Country VARCHAR,AddressCertified VARCHAR,C_SuspectFlag VARCHAR,c_CrossBrandFlag VARCHAR,c_primaryphysicalstorejc VARCHAR,c_primaryphysicalstorefa VARCHAR,c_loyaltyflag VARCHAR,c_returnratefa VARCHAR,c_returnratejc VARCHAR,c_plccapplicationstatus VARCHAR,c_plccclosedate VARCHAR,c_plccflag VARCHAR,c_plccsignupchannel VARCHAR,c_plccsignupdate VARCHAR,c_plccsignupstore VARCHAR,c_plccstatus VARCHAR,c_totalrevenue12fm VARCHAR,c_totalrevenuefa12fm VARCHAR,c_totalrevenuejc12fm VARCHAR,c_loyaltyid VARCHAR,c_loyaltyjcccpoints VARCHAR,c_clvrevenue1yearfa VARCHAR,c_clvrevenue1yearjc VARCHAR,c_loyaltytier VARCHAR,CLVDecile VARCHAR,FA_SaleRevenue VARCHAR,c_dsclvrevenue1yearfa VARCHAR,ltb_a_value VARCHAR,c_dsdiscountsensitivitysegmentjc VARCHAR,c_dsflex1jc VARCHAR,c_lasttransactiondatejc VARCHAR,SourceID VARCHAR,Brand VARCHAR,IQ_DataSet VARCHAR
);

UPDATE PUBLIC.LP_S3_CREDENTIALS
SET isActive = 2
    ,FileName = 'LP_JCR2503_IQ'
    ,DestinationTable = 'LP_JCR2503_IQ'
WHERE ConfigID = 21;

SELECT * FROM PUBLIC.LP_S3_CREDENTIALS
WHERE isActive = 2;

CALL PUBLIC.LP_IMPORT_S3FILES_BYDEMAND();
--CALL PUBLIC.LP_IMPORT_S3FILES_BYDEMAND_VALIDATION();

SELECT COUNT(*) FROM JCREW.LP_JCR2503_IQ;
--6596595

SELECT Priority,COUNT(*)
FROM JCREW.LP_JCR2503_IQ
GROUP BY Priority
ORDER BY Priority;

--DROP TABLE LP_JCR2503_MailFile;

CALL JCREW.LP_01_MAILFILE_JCR2503('No','JCR2503');

DELETE FROM JCREW.LP_JCR2503_MailFile
WHERE MasterCustomerID NOT IN (
    SELECT MASTERCUSTOMERID
    FROM JCREW.LP_JCR2503_MailFile
    WHERE Priority = 2
    AND c_dsclvrevenue1yearfa != ''
    ORDER BY CAST(CLVDecile AS INT), CAST(c_dsclvrevenue1yearfa AS FLOAT) DESC
    LIMIT 200000
)
AND Priority = 2
;

DELETE FROM JCREW.LP_JCR2503_MailFile
WHERE MasterCustomerID NOT IN (
    SELECT MASTERCUSTOMERID
    FROM JCREW.LP_JCR2503_MailFile
    WHERE Priority = 3
    AND FA_SaleRevenue != ''
    ORDER BY CAST(FA_SaleRevenue AS INT) DESC
    LIMIT 100000
)
AND Priority = 3
;

SELECT Priority,COUNT(*)
FROM JCREW.LP_JCR2503_MailFile
GROUP BY Priority
ORDER BY Priority;

SELECT Priority,COUNT(*)
FROM JCREW.LP_JCR2503_MailFile
WHERE c_plccflag = 'Y'
AND Priority > 0
GROUP BY Priority
ORDER BY Priority;

SELECT COUNT(*),MIN(CAST(c_dsclvrevenue1yearfa AS FLOAT)),MAX(CAST(c_dsclvrevenue1yearfa AS FLOAT)),CLVDecile
FROM JCREW.LP_JCR2503_MailFile
WHERE Priority = 2
GROUP BY CLVDecile;

SELECT COUNT(*),MIN(CAST(FA_SaleRevenue AS FLOAT)),MAX(CAST(FA_SaleRevenue AS FLOAT))
FROM JCREW.LP_JCR2503_MailFile
WHERE Priority = 3;

SELECT COUNT(*) FROM JCREW.LP_JCR2503_MailFile;
--1000641

COPY INTO @INTERNAL_JC/Accuzip/LP_JCR2503_MailFile.csv.gz
FROM
(
    SELECT LineID,FullName AS First,Address1 AS Address,Address2,City,State AS St,Zip,'US' AS Country
    FROM JCREW.LP_JCR2503_MailFile
    ORDER BY Zip
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 2000000000
FILE_FORMAT = (FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF=(''))
;
--1000641

DELETE FROM PUBLIC.LP_AZ_GUID WHERE JobID = 'JCR2503';
INSERT INTO PUBLIC.LP_AZ_GUID
SELECT 'JCR2503','25092464-76A9-4676-A1D7-83E8EE9EAFBF',CURRENT_TIMESTAMP;

SELECT * FROM PUBLIC.LP_AZ_GUID
WHERE JobID LIKE 'JCR2503%';

--DROP TABLE JCREW.LP_JCR2503_MAILFILE_NCOA;

SELECT COUNT(*) AS Counts,'MailFile' AS TableType FROM JCREW.LP_JCR2503_MAILFILE
UNION ALL
SELECT COUNT(*) AS Counts,'NCOA' AS TableType FROM JCREW.LP_JCR2503_MAILFILE_NCOA;

SELECT * FROM JCREW.LP_JCR2503_MAILFILE_NCOA
LIMIT 5;

UPDATE JCREW.LP_JCR2503_MAILFILE
SET SUPPRESSIONTYPE = 'ADR'
WHERE Priority IN (-4);

UPDATE JCREW.LP_JCR2503_MAILFILE
SET SUPPRESSIONTYPE = 'HH'
WHERE Priority IN (-5,-2);

SELECT Priority,SUPPRESSIONTYPE,DEDUPETYPE,COUNT(*)
FROM JCREW.LP_JCR2503_MAILFILE
GROUP BY Priority,SUPPRESSIONTYPE,DEDUPETYPE
ORDER BY PRIORITY;

CALL PUBLIC.LP_02_AccuzipOutput_JC('JCREW','LP_JCR2503_Mailfile',0);
CALL PUBLIC.LP_05_UPD_DDNC('JCREW','LP_JCR2503_Mailfile');
CALL PUBLIC.LP_06_UPD_Prison('JCREW','LP_JCR2503_Mailfile');
CALL PUBLIC.LP_07_UPD_DMA('JCREW','LP_JCR2503_Mailfile','''Prospects''');
CALL PUBLIC.LP_08_UPD_BADDATA('JCREW','LP_JCR2503_Mailfile');
CALL PUBLIC.LP_09_UPD_OBSCENE('JCREW','LP_JCR2503_Mailfile');
CALL PUBLIC.LP_10_UPD_SUPPRESSION('JCREW','LP_JCR2503_Mailfile');
CALL PUBLIC.LP_11_UPD_DUPLICATE('JCREW','LP_JCR2503_Mailfile');
CALL PUBLIC.LP_12_UPD_Multi('JCREW','LP_JCR2503_Mailfile','500',0);

UPDATE LP_JCR2503_Mailfile
SET isstateSuppress = 1
WHERE STATE_C IN ('AA', 'AE', 'AP', 'AS', 'FM', 'GU', 'MH', 'MP', 'PR', 'PW', 'VI');
-- 3168

ALTER TABLE LP_JCR2503_Mailfile ADD isAddressPOBox INT; 

UPDATE LP_JCR2503_Mailfile MF 
SET isAddressPOBox  =1
    ,isBlacklisted = 1
WHERE LineID IN (
             SELECT LineID
             FROM LP_JCR2301_MailFile
             WHERE STREET_C LIKE '%PO%BOX%'
             AND PRIORITY >0);
--7

--Reset isSelected
UPDATE JCREW.LP_JCR2503_MAILFILE
SET isSelected=0
WHERE isSelected = 1;

UPDATE JCREW.LP_JCR2503_MAILFILE
SET isSelected=1
WHERE (
    COALESCE(isCASSDrop,0)     = 0 
AND COALESCE(isDpvDrop,0)      = 0 
AND COALESCE(isStateSuppress,0) = 0 
AND COALESCE(isANKLink,0)       = 0 
AND COALESCE(isVacant,0)        = 0 
AND COALESCE(isBaddata,0)       = 0 
AND COALESCE(isObscene,0)       = 0 
AND COALESCE(isDDNC,0)          = 0 
AND COALESCE(isPrison,0)        = 0 
AND COALESCE(isHHSuppression,0) = 0 
AND COALESCE(isADRSuppression,0)= 0 
AND COALESCE(isPERSuppression,0)= 0 
AND COALESCE(isHHDuplicate,0)   = 0 
AND COALESCE(isDMASuppress,0)   = 0 
AND COALESCE(isRadiusDrop,0)    = 0
AND COALESCE(isAddressPOBox,0)  = 0
AND Priority >0
);
--482779

UPDATE JCREW.LP_JCR2503_MAILFILE
SET isSelected=1
WHERE Priority = 0;
--14

SELECT Priority,COUNT(*)
FROM LP_JCR2503_MAILFILE
WHERE isSelected = 1
GROUP BY PRIORITY
ORDER BY PRIORITY;

SELECT Priority,COUNT(*)
FROM LP_JCR2503_MailFile
WHERE isSelected = 1 AND c_plccflag = 'Y'
GROUP BY Priority
ORDER BY Priority;

SELECT Priority,COUNT(*)
FROM LP_JCR2503_MailFile
WHERE isSelected = 1 AND COALESCE(c_plccflag,'') = ''
GROUP BY Priority
ORDER BY Priority;

--Final Instructions
UPDATE JCREW.LP_JCR2503_MailFile
SET isMailed = 0
    ,isHoldout = 0
    ,FileName = NULL
WHERE (isMailed = 1 OR isholdout = 1);
--

ALTER TABLE LP_JCR2503_MailFile ALTER COLUMN KeyCode VARCHAR(32);

CREATE OR REPLACE TEMPORARY TABLE tmpPriority1_Control AS
SELECT LineID
FROM JCREW.LP_JCR2503_MailFile
WHERE isSelected = 1 AND Priority = 1
AND NOT ((STREET_C = '32 STAR ISLAND RD' AND STATE_C = 'NY' AND ZIP_C = '11954-5271')
OR (STREET_C = '207 MESEROLE AVE' AND STATE_C = 'NY' AND ZIP_C = '11222-2432')
OR (STREET_C = '4450 WITMER INDUSTRIAL EST STE 4' AND STATE_C = 'NY' AND ZIP_C = '14305-1391')
OR (STREET_C = '9 SCOBIE DR' AND STATE_C = 'NY' AND ZIP_C = '12550-3258')
OR (STREET_C = '2558 W 16TH ST' AND STATE_C = 'IL' AND ZIP_C = '60608-1720')
OR (STREET_C = '5102 21ST ST STE 3B' AND STATE_C = 'NY' AND ZIP_C = '11101-5838')
OR (STREET_C = '400 PLAZA DR STE 102' AND STATE_C = 'NJ' AND ZIP_C = '07094-3605')
OR (STREET_C = '4000 NW SAINT HELENS RD' AND STATE_C = 'OR' AND ZIP_C = '97210-1437')
OR (STREET_C = '25 Washington Ave Ste 2200' AND STATE_C = 'NY' AND ZIP_C = '11205-1202')
OR (STREET_C = '6900 NORTHPARK BLVD STE G' AND STATE_C = 'NC' AND ZIP_C = '28216-1393'))
ORDER BY RANDOM()
LIMIT 21883
;

UPDATE LP_JCR2503_MailFile AS MF
SET MF.isHoldout = 1
    ,MF.FileName = 'JCR2503_Holdout'
    ,MF.KeyCode = 'TOP_H'
FROM tmpPriority1_Control AS tmp
WHERE MF.LineID = tmp.LineID
AND MF.isSelected = 1 AND MF.Priority = 1; 
--21883

UPDATE LP_JCR2503_MailFile AS MF
SET MF.isMailed = 1
    ,MF.FileName = 'JCR2503'
    ,MF.KeyCode = CASE Priority
                        WHEN 0 THEN 'SEED'
                        WHEN 1 THEN 'TOP'
                  END
WHERE MF.isSelected = 1 AND Priority IN (0,1) AND COALESCE(isHoldout,0) = 0
AND NOT ((STREET_C = '32 STAR ISLAND RD' AND STATE_C = 'NY' AND ZIP_C = '11954-5271')
OR (STREET_C = '207 MESEROLE AVE' AND STATE_C = 'NY' AND ZIP_C = '11222-2432')
OR (STREET_C = '4450 WITMER INDUSTRIAL EST STE 4' AND STATE_C = 'NY' AND ZIP_C = '14305-1391')
OR (STREET_C = '9 SCOBIE DR' AND STATE_C = 'NY' AND ZIP_C = '12550-3258')
OR (STREET_C = '2558 W 16TH ST' AND STATE_C = 'IL' AND ZIP_C = '60608-1720')
OR (STREET_C = '5102 21ST ST STE 3B' AND STATE_C = 'NY' AND ZIP_C = '11101-5838')
OR (STREET_C = '400 PLAZA DR STE 102' AND STATE_C = 'NJ' AND ZIP_C = '07094-3605')
OR (STREET_C = '4000 NW SAINT HELENS RD' AND STATE_C = 'OR' AND ZIP_C = '97210-1437')
OR (STREET_C = '25 Washington Ave Ste 2200' AND STATE_C = 'NY' AND ZIP_C = '11205-1202')
OR (STREET_C = '6900 NORTHPARK BLVD STE G' AND STATE_C = 'NC' AND ZIP_C = '28216-1393'));
--196952

CREATE OR REPLACE TEMPORARY TABLE tmpPriority2 AS
SELECT LineID
FROM JCREW.LP_JCR2503_MailFile
WHERE isSelected = 1 AND Priority = 2
AND NOT ((STREET_C = '32 STAR ISLAND RD' AND STATE_C = 'NY' AND ZIP_C = '11954-5271')
OR (STREET_C = '207 MESEROLE AVE' AND STATE_C = 'NY' AND ZIP_C = '11222-2432')
OR (STREET_C = '4450 WITMER INDUSTRIAL EST STE 4' AND STATE_C = 'NY' AND ZIP_C = '14305-1391')
OR (STREET_C = '9 SCOBIE DR' AND STATE_C = 'NY' AND ZIP_C = '12550-3258')
OR (STREET_C = '2558 W 16TH ST' AND STATE_C = 'IL' AND ZIP_C = '60608-1720')
OR (STREET_C = '5102 21ST ST STE 3B' AND STATE_C = 'NY' AND ZIP_C = '11101-5838')
OR (STREET_C = '400 PLAZA DR STE 102' AND STATE_C = 'NJ' AND ZIP_C = '07094-3605')
OR (STREET_C = '4000 NW SAINT HELENS RD' AND STATE_C = 'OR' AND ZIP_C = '97210-1437')
OR (STREET_C = '25 Washington Ave Ste 2200' AND STATE_C = 'NY' AND ZIP_C = '11205-1202')
OR (STREET_C = '6900 NORTHPARK BLVD STE G' AND STATE_C = 'NC' AND ZIP_C = '28216-1393'))
ORDER BY CAST(CLVDECILE AS INT),CAST(c_dsclvrevenue1yearfa AS FLOAT) DESC
LIMIT 158062
;

UPDATE LP_JCR2503_MailFile AS MF
SET MF.isMailed = 1
    ,MF.FileName = 'JCR2503'
    ,MF.KeyCode = 'REACT'
FROM tmpPriority2 AS tmp
WHERE MF.LineID = tmp.LineID
AND MF.isSelected = 1 AND MF.Priority = 2; 
--158062

CREATE OR REPLACE TEMPORARY TABLE tmpPriority2_Control AS
SELECT LineID
FROM JCREW.LP_JCR2503_MailFile
WHERE isSelected = 1 AND Priority = 2 AND COALESCE(isMailed,0) = 0
AND NOT ((STREET_C = '32 STAR ISLAND RD' AND STATE_C = 'NY' AND ZIP_C = '11954-5271')
OR (STREET_C = '207 MESEROLE AVE' AND STATE_C = 'NY' AND ZIP_C = '11222-2432')
OR (STREET_C = '4450 WITMER INDUSTRIAL EST STE 4' AND STATE_C = 'NY' AND ZIP_C = '14305-1391')
OR (STREET_C = '9 SCOBIE DR' AND STATE_C = 'NY' AND ZIP_C = '12550-3258')
OR (STREET_C = '2558 W 16TH ST' AND STATE_C = 'IL' AND ZIP_C = '60608-1720')
OR (STREET_C = '5102 21ST ST STE 3B' AND STATE_C = 'NY' AND ZIP_C = '11101-5838')
OR (STREET_C = '400 PLAZA DR STE 102' AND STATE_C = 'NJ' AND ZIP_C = '07094-3605')
OR (STREET_C = '4000 NW SAINT HELENS RD' AND STATE_C = 'OR' AND ZIP_C = '97210-1437')
OR (STREET_C = '25 Washington Ave Ste 2200' AND STATE_C = 'NY' AND ZIP_C = '11205-1202')
OR (STREET_C = '6900 NORTHPARK BLVD STE G' AND STATE_C = 'NC' AND ZIP_C = '28216-1393'))
ORDER BY CAST(CLVDECILE AS INT),CAST(c_dsclvrevenue1yearfa AS FLOAT) DESC
LIMIT 15806
;

UPDATE LP_JCR2503_MailFile AS MF
SET MF.isHoldout = 1
    ,MF.FileName = 'JCR2503_Holdout'
    ,MF.KeyCode = 'REACT_H'
FROM tmpPriority2_Control AS tmp
WHERE MF.LineID = tmp.LineID
AND MF.isSelected = 1 AND MF.Priority = 2; 
--15806

CREATE OR REPLACE TEMPORARY TABLE tmpPriority3 AS
SELECT LineID
FROM JCREW.LP_JCR2503_MailFile
WHERE isSelected = 1 AND Priority = 3
AND NOT ((STREET_C = '32 STAR ISLAND RD' AND STATE_C = 'NY' AND ZIP_C = '11954-5271')
OR (STREET_C = '207 MESEROLE AVE' AND STATE_C = 'NY' AND ZIP_C = '11222-2432')
OR (STREET_C = '4450 WITMER INDUSTRIAL EST STE 4' AND STATE_C = 'NY' AND ZIP_C = '14305-1391')
OR (STREET_C = '9 SCOBIE DR' AND STATE_C = 'NY' AND ZIP_C = '12550-3258')
OR (STREET_C = '2558 W 16TH ST' AND STATE_C = 'IL' AND ZIP_C = '60608-1720')
OR (STREET_C = '5102 21ST ST STE 3B' AND STATE_C = 'NY' AND ZIP_C = '11101-5838')
OR (STREET_C = '400 PLAZA DR STE 102' AND STATE_C = 'NJ' AND ZIP_C = '07094-3605')
OR (STREET_C = '4000 NW SAINT HELENS RD' AND STATE_C = 'OR' AND ZIP_C = '97210-1437')
OR (STREET_C = '25 Washington Ave Ste 2200' AND STATE_C = 'NY' AND ZIP_C = '11205-1202')
OR (STREET_C = '6900 NORTHPARK BLVD STE G' AND STATE_C = 'NC' AND ZIP_C = '28216-1393'))
ORDER BY CAST(FA_SaleRevenue AS FLOAT) DESC
LIMIT 65000
;

UPDATE LP_JCR2503_MailFile AS MF
SET MF.isMailed = 1
    ,MF.FileName = 'JCR2503'
    ,MF.KeyCode = 'FACT'
FROM tmpPriority3 AS tmp
WHERE MF.LineID = tmp.LineID
AND MF.isSelected = 1 AND MF.Priority = 3; 
--65000

CREATE OR REPLACE TEMPORARY TABLE tmpPriority3_Control AS
SELECT LineID
FROM JCREW.LP_JCR2503_MailFile
WHERE isSelected = 1 AND Priority = 3 AND COALESCE(isMailed,0) = 0
AND NOT ((STREET_C = '32 STAR ISLAND RD' AND STATE_C = 'NY' AND ZIP_C = '11954-5271')
OR (STREET_C = '207 MESEROLE AVE' AND STATE_C = 'NY' AND ZIP_C = '11222-2432')
OR (STREET_C = '4450 WITMER INDUSTRIAL EST STE 4' AND STATE_C = 'NY' AND ZIP_C = '14305-1391')
OR (STREET_C = '9 SCOBIE DR' AND STATE_C = 'NY' AND ZIP_C = '12550-3258')
OR (STREET_C = '2558 W 16TH ST' AND STATE_C = 'IL' AND ZIP_C = '60608-1720')
OR (STREET_C = '5102 21ST ST STE 3B' AND STATE_C = 'NY' AND ZIP_C = '11101-5838')
OR (STREET_C = '400 PLAZA DR STE 102' AND STATE_C = 'NJ' AND ZIP_C = '07094-3605')
OR (STREET_C = '4000 NW SAINT HELENS RD' AND STATE_C = 'OR' AND ZIP_C = '97210-1437')
OR (STREET_C = '25 Washington Ave Ste 2200' AND STATE_C = 'NY' AND ZIP_C = '11205-1202')
OR (STREET_C = '6900 NORTHPARK BLVD STE G' AND STATE_C = 'NC' AND ZIP_C = '28216-1393'))
ORDER BY CAST(FA_SaleRevenue AS FLOAT) DESC
LIMIT 6500
;

UPDATE LP_JCR2503_MailFile AS MF
SET MF.isHoldout = 1
    ,MF.FileName = 'JCR2503_Holdout'
    ,MF.KeyCode = 'FACT_H'
FROM tmpPriority3_Control AS tmp
WHERE MF.LineID = tmp.LineID
AND MF.isSelected = 1 AND MF.Priority = 3; 
--6500
 
SELECT Priority,isMailed,isHoldout,COUNT(*),FileName,KeyCode
FROM JCREW.LP_JCR2503_MailFile
WHERE isMailed = 1 OR isholdout = 1
GROUP BY Priority,isMailed,isHoldout,FileName,KeyCode
ORDER BY Priority,isMailed DESC,isHoldout,FileName;

SELECT FileName,COUNT(*)
FROM JCREW.LP_JCR2503_MailFile
WHERE isMailed = 1 OR isholdout = 1
GROUP BY FileName;

--CALL JCREW.LP_ExportOutputFile('LP_JCR2503_MailFile','JCR2503');
--CALL JCREW.LP_ExportOutputFile('LP_JCR2503_MailFile','JCR2503_Holdout');
--CALL JCREW.LP_ExportOutputFile_WITH_SaleRevenue('LP_JCR2503_MailFile','JCR2503');

--ALTER TABLE LP_JCR2503_MailFile DROP COLUMN UPC_Prefix;
ALTER TABLE LP_JCR2503_MailFile ADD UPC_Prefix VARCHAR;

CREATE OR REPLACE TEMPORARY TABLE tmpRanking
AS
SELECT LineID,Priority,ROW_NUMBER() OVER(PARTITION BY Priority ORDER BY RANDOM()) AS RK
FROM LP_JCR2503_MailFile
WHERE (ismailed = 1 OR isHoldout =1) AND Priority IN (1,2,3)
;

SELECT * FROM tmpRanking ORDER BY RK,Priority;

CALL PUBLIC.LP_AGL_ADDLINEID('JCREW','LP_JCR2503_GOLD_PROMOCODES');
CALL PUBLIC.LP_AGL_ADDLINEID('JCREW','LP_JCR2503_REACTIVATED_PROMOCODE');
CALL PUBLIC.LP_AGL_ADDLINEID('JCREW','LP_JCR2503_FACTORY_PROMOCODE');

SELECT COUNT(*) FROM LP_JCR2503_GOLD_PROMOCODES;
SELECT COUNT(*) FROM LP_JCR2503_REACTIVATED_PROMOCODE;
SELECT COUNT(*) FROM LP_JCR2503_FACTORY_PROMOCODE;

CREATE OR REPLACE TEMPORARY TABLE tmpUPC_Prefix
AS
SELECT MF.LineID,PC.PromoCode AS UPC_Prefix,MF.Priority
FROM tmpRanking AS MF
INNER JOIN LP_JCR2503_GOLD_PROMOCODES AS PC
    ON MF.RK = PC.LineID
WHERE MF.Priority = 1
UNION ALL
SELECT MF.LineID,PC.PromoCode AS UPC_Prefix,MF.Priority
FROM tmpRanking AS MF
INNER JOIN LP_JCR2503_REACTIVATED_PROMOCODE AS PC
    ON MF.RK = PC.LineID
WHERE MF.Priority = 2
UNION ALL
SELECT MF.LineID,PC.PromoCode AS UPC_Prefix,MF.Priority
FROM tmpRanking AS MF
INNER JOIN LP_JCR2503_FACTORY_PROMOCODE AS PC
    ON MF.RK = PC.LineID
WHERE MF.Priority = 3
;

UPDATE LP_JCR2503_MailFile MF
SET MF.UPC_Prefix = PF.UPC_Prefix
FROM tmpUPC_Prefix AS PF
WHERE MF.LineID = PF.LineID
;

SELECT DISTINCT Priority,LEFT(UPC_PREFIX,3),KeyCOde
FROM LP_JCR2503_MailFile
WHERE isMailed = 1;

CALL JCREW.LP_EXPORTOUTPUTFILE_WITH_UPC_PREFIX('LP_JCR2503_MailFile','JCR2503');
CALL JCREW.LP_EXPORTOUTPUTFILE_WITH_UPC_PREFIX('LP_JCR2503_MailFile','JCR2503_Holdout');

UPDATE LP_JCR2503_MAILFILE SET FILENAME = CONCAT(FILENAME,'_',CASE WHEN KEYCODE = 'SEED' THEN 'TOP' ELSE KEYCODE END)
WHERE isMailed = 1
;

SELECT FileName,COUNT(*)
FROM LP_JCR2503_MailFile
WHERE isMailed = 1
GROUP BY FileName
ORDER BY FileName;

CALL JCREW.LP_EXPORTOUTPUTFILE_WITH_UPC_PREFIX('LP_JCR2503_MailFile','JCR2503_TOP');
CALL JCREW.LP_EXPORTOUTPUTFILE_WITH_UPC_PREFIX('LP_JCR2503_MailFile','JCR2503_REACT');
CALL JCREW.LP_EXPORTOUTPUTFILE_WITH_UPC_PREFIX('LP_JCR2503_MailFile','JCR2503_FACT');