CALL LAFAYETTE.LP_CO_PivotHistory();

SELECT "CustType",COUNT(*) AS "Counts"
FROM LAF_LP_CO_V6_Customer
GROUP BY "CustType";

CALL LAFAYETTE.LP_CO_COLUMNSFILLRATE('LAF_LP_CO_V6_CUSTOMER');

SELECT * FROM LAF_LP_CO_V6_Customer;

CALL LAFAYETTE.LP_CO_COLUMNSFILLRATE('LAF_LP_CO_V6_ORGANIZATION');

CALL LAFAYETTE.LP_CO_COLUMNSFILLRATE('LAF_LP_CO_V6_PRODUCT');

CALL LAFAYETTE.LP_CO_COLUMNSFILLRATE('LAF_LP_CO_V6_SEED');

CALL LAFAYETTE.LP_CO_COLUMNSFILLRATE('LAF_LP_CO_V6_TRANSACTION');